server:
  port: 8080
  servlet:
    context-path: /devweek

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    genereate-ddl: false
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para a DevWeek DIO - Santander
  version: 1.0